// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
// Created on Fri Jul 03 21:46:31 2026

background background_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.resetN(resetN_sig) ,	// input  resetN_sig
	.startOfFrame(startOfFrame_sig) ,	// input  startOfFrame_sig
	.current_state(current_state_sig) ,	// input [2:0] current_state_sig
	.pixelX(pixelX_sig) ,	// input [10:0] pixelX_sig
	.pixelY(pixelY_sig) ,	// input [10:0] pixelY_sig
	.address(address_sig) ,	// input [18:0] address_sig
	.background_dr(background_dr_sig) ,	// output  background_dr_sig
	.BG_RGB(BG_RGB_sig) 	// output [7:0] BG_RGB_sig
);

