// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
// Created on Fri Jul 03 22:00:59 2026

TOP_VGA_DEMO TOP_VGA_DEMO_inst
(
	.CLOCK_50(CLOCK_50_sig) ,	// input  CLOCK_50_sig
	.PS2_CLK(PS2_CLK_sig) ,	// input  PS2_CLK_sig
	.PS2_DAT(PS2_DAT_sig) ,	// input  PS2_DAT_sig
	.resetN_pin(resetN_pin_sig) ,	// input  resetN_pin_sig
	.KEY(KEY_sig) ,	// input [3:3] KEY_sig
	.AUDIN(AUDIN_sig) ,	// input [1:2] AUDIN_sig
	.HEX0(HEX0_sig) ,	// output [6:0] HEX0_sig
	.OVGA(OVGA_sig) ,	// output [28:0] OVGA_sig
	.HEX1(HEX1_sig) ,	// output [6:0] HEX1_sig
	.HEX2(HEX2_sig) ,	// output [6:0] HEX2_sig
	.HEX3(HEX3_sig) ,	// output [6:0] HEX3_sig
	.HEX4(HEX4_sig) ,	// output [6:0] HEX4_sig
	.HEX5(HEX5_sig) ,	// output [6:0] HEX5_sig
	.redLight(redLight_sig) ,	// output  redLight_sig
	.yellowLight(yellowLight_sig) ,	// output  yellowLight_sig
	.greenLight(greenLight_sig) ,	// output  greenLight_sig
	.AUDOUT(AUDOUT_sig) ,	// output [4:7] AUDOUT_sig
	.BG_RGB(BG_RGB_sig) ,	// output [7:0] BG_RGB_sig
	.boardersDrawReq(boardersDrawReq_sig) 	// output  boardersDrawReq_sig
);

